apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization        
generatorOptions:
 disableNameSuffixHash: true
configMapGenerator:
  - name: flask-postgres-ready-sh
    files:
      - ./scripts/ready.sh
resources:                 
  - ns.yaml
  - postgres-password.yaml
  - postgres.yaml
  - flask-postgres-config.yaml
