apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization        
generatorOptions:
 disableNameSuffixHash: true
configMapGenerator:
  - name: flask-postgres-ready-sh
    files:
      - ./scripts/ready.sh
  - name: flask-postgres-sqls
    files:
      - ./scripts/download-sqls.sh
resources:
  - ns.yaml
  - postgres-password.yaml
  - postgres.yaml
  - flask-postgres-config.yaml
  - py-flask.yaml
