apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flask-postgres
  namespace: perf-test
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: flask-postgres
    creationPolicy: Owner
  data:
  - secretKey: flask-postgres
    remoteRef:
      key: flask-postgres
