---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-flask
  namespace: perf-test
spec:
  selector:
    matchLabels:
      app: py-flask
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: py-flask
    spec:
      containers:
        - name: py-flask
          image: public.ecr.aws/i7p4t6o8/py-flask-perf:1.1.1
          ports:
            - name: py-flask-port
              containerPort: 5000
          resources:
            limits:
              memory: 64Mi
              cpu: 20m
            requests:
              memory: 64Mi
              cpu: 20m
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: flask-postgres-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flask-postgres
                  key: flask-postgres
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: flask-postgres-config
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: flask-postgres-config
                  key: DB_HOST
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            periodSeconds: 20
            timeoutSeconds: 5
            initialDelaySeconds: 140
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            periodSeconds: 20
            timeoutSeconds: 5
            initialDelaySeconds: 140
---
apiVersion: v1
kind: Service
metadata:
  name: py-flask-service
  namespace: perf-test
spec:
  selector:
    app: py-flask
  ports:
    - name: py-flask
      protocol: TCP
      port: 5001
      targetPort: 5000